version: "3.9"

services:
  php:
    container_name: php
    image: php
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "8002:80"
    volumes:
      - ./scripts:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor

volumes:
  persistent:
